services:
  webviewer:
    build: ./webviewer
    container_name: django_web
    volumes:
      - ./webviewer:/usr/src/app
      - data-volume:/vol/data
      - static_data:/vol/webviewer
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    entrypoint: /entrypoint.sh

volumes:
  static_data:
  data-volume:
    external: true