version: '3.8'

services:
  webviewer:
    build: ./webviewer
    container_name: django_web
    command: bash -c "
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./webviewer:/usr/src/app
      - data-volume:/vol/data
      - static_data:/vol/webviewer
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"

volumes:
  static_data:
  data-volume:
    external: true